---
deployment:
  tasks:
    - pnpm install --frozen-lockfile
    - pnpm build
    - mkdir -p $HOME/repositories/notion-widgets/apps/widget-server/dist/tmp
    - touch $HOME/repositories/notion-widgets/apps/widget-server/dist/tmp/restart.txt